### ISSUE TITLE
Makefile: should ensure that dependies is set and they are up to date

### ISSUE THREAD

**Issue by Heather** [lolisa/Cirno#14]
- Alternatively: switch to cmake (there are cool techniques to resolve dependies)
 - Alternatively: add dependies as submodules

I can jump on it some later.

**Comment by lolisa** [comment]
Dont worry, I will get this, I definitely need to learn proper make sooner or later

**Comment by Heather** [comment]
@lolisa I don't worry =) It's just todo list
